=== acdcjunior/richfaces-3.3.x/branches/community/3.3.X/cdk/generator/src/main/resources/META-INF/schema/component-config.dtd
<!-- Defenition of component configuration for generator 
	PUBLIC-ID "-//AJAX4JSF//CDK Generator config/EN"
	SYSTEM-ID http://labs.jboss.com/jbossrichfaces/component-config.dtd -->
<!-- Root element for components and renderers  -->	
<!ELEMENT components (component*,renderer*,listener*,validator*,converter*,function*) >
<!-- Component description with common properties, tags and renderers descriptions  -->	
<!ELEMENT component (name,family?,classname?,superclass?,test*,description?,displayname?,icon?,facet*,renderer*,tag?,taghandler?,(include|properties|property)*)>
<!-- Validator description with properties and tags -->
<!ELEMENT validator (id,classname?,superclass?,test*,description?,displayname?,icon?,tag?,taghandler?,(include|properties|property)*)>
<!-- Validator description with properties and tags -->
<!ELEMENT converter (id,classname?,superclass?,test*,description?,displayname?,icon?,tag?,taghandler?,(include|properties|property)*)>

<!ELEMENT function (name,description?,method)>

<!-- components with generate=false not produce component class, 
     use for describe superclasses for other components -->
<!ATTLIST component
	generate (true|false) "true" 
	>
	
<!-- validators with generate=false do not generate a class -->
<!ATTLIST validator
	generate (true|false) "true" 
	>
	
<!-- converters with generate=false do not generate a class -->
<!ATTLIST converter
	generate (true|false) "true" 
	>

<!-- Common component parameters -->
<!-- Name of component/renderer/property -->
<!ELEMENT name (#PCDATA)>
<!-- Id of the validator/converter -->
<!ELEMENT id (#PCDATA)>
<!-- Component family -->
<!ELEMENT family (#PCDATA)>
<!-- Element Description for config files -->
<!ELEMENT description ANY>
<!-- Element Dispaly name , for config files -->
<!ELEMENT displayname ANY>
<!-- Element icon image , for config files -->
<!ELEMENT icon (#PCDATA)>
<!-- component allowed facet  name , for config files -->
<!ELEMENT facet (name,displayname?,description?)>
<!-- Full name of Java class -->
<!ELEMENT classname (#PCDATA)>
<!-- Full name of Java super class -->
<!ELEMENT superclass (#PCDATA)>
<!-- Define renderer for this component -->
<!ELEMENT renderer (name,family?,(classname|template),superclass?,description?,displayname?,icon?,facet?,renderkit?)>
<!-- Define render kit Id for renderer -->
<!ELEMENT renderkit (#PCDATA)>
<!-- Template file name -->
<!ELEMENT template (#PCDATA)>
<!-- Fully-qualified method name and signature -->
<!ELEMENT method (#PCDATA)>

<!ATTLIST renderer
	generate (true|false) "false" 
	override (true|false) "false" 
	>

<!-- Define JSP tag for this component -->
<!ELEMENT tag (name,classname,superclass?,test*,taglib?,description?,displayname?,icon?)>
<!ATTLIST tag
	generate (true|false) "true" 
	bodyContent (JSP|empty) "JSP" 
	>

<!ELEMENT test (classname?,superclassname?)>
<!--!ELEMENT classname (#PCDATA)-->
<!ELEMENT superclassname (#PCDATA)>

<!-- Define JSP tag for this component -->
<!ELEMENT taghandler (name?,classname,superclass?,description?,displayname?,icon?)>
<!ATTLIST taghandler
	generate (true|false) "false" 
	>

<!ELEMENT listener (name,listenerclass,componentclass,eventclass,methodname?,tag?,taghandler?,property*)>

<!ELEMENT listenerclass (#PCDATA)>
<!ELEMENT eventclass (#PCDATA)>
<!ELEMENT componentclass (#PCDATA)>
<!ELEMENT methodname (#PCDATA)>

<!-- Short name of taglib for this tag - for generate set of taglibs in single task -->
<!ELEMENT taglib (#PCDATA)>

<!-- proprties group for included entity -->
<!ELEMENT properties ((include|properties|property)*)>

<!-- Define single property for this component -->
<!ELEMENT property (name,classname?,description?,defaultvalue?,methodargs?,returntype?,alias*)>

<!-- default value for property -->
<!ELEMENT defaultvalue (#PCDATA)>

<!-- comma-separated list of method call parameters classes for Method-binded property -->
<!ELEMENT methodargs (#PCDATA)>

<!-- return type for method call parameters classes for Method-binded property -->
<!ELEMENT returntype (#PCDATA)>

<!-- alias for property in JSP tag -->
<!ELEMENT alias (#PCDATA)>

<!ATTLIST property 
	el (true|false) "true"
	elonly (true|false) "false"
	hidden (true|false) "false"
	exist (true|false) "false"
	raw (true|false) "false"
	existintag (true|false) "false"
	attachedstate (true|false) "false"
	transient (true|false) "false"
	required (true|false) "false"
	disabled (true|false) "false"	
	>
<!-- include pre-defined properties set -->
<!ELEMENT include EMPTY >
<!ATTLIST include 
      href CDATA #REQUIRED
>

<!-- pre-defined entities for common components properties -->
<!ENTITY html_attributes   PUBLIC "html_universal_attributes" "entities/html_universal_attributes.ent">	
<!-- pre-defined entities for common component events -->
<!ENTITY html_events   PUBLIC "html_events" "entities/html_events.ent">	
<!-- pre-defined entities for common controls' events -->
<!ENTITY html_control_events   PUBLIC "html_control_events" "entities/html_control_events.ent">	
<!-- -->
<!ENTITY ajax_region_attributes PUBLIC "ajax_region_attributes" "entities/ajax_region_attributes.ent">
<!-- -->
<!ENTITY ajax_component_attributes PUBLIC "ajax_component_attributes" "entities/ajax_component_attributes.ent">
<!-- -->
<!ENTITY ajax_output_attributes PUBLIC "ajax_output_attributes" "entities/ajax_output_attributes.ent">
<!-- -->
<!ENTITY ajax_dnd_attributes PUBLIC "ajax_dnd_attributes" "entities/ajax_dnd_attributes.ent">
<!-- -->
<!ENTITY dropzone_attributes PUBLIC "dropzone_attributes" "entities/dropzone_attributes.ent">
<!-- -->
<!ENTITY draggable_attributes PUBLIC "draggable_attributes" "entities/draggable_attributes.ent">

<!-- imported from myfaces -->

<!-- -->
<!ENTITY validator_min_max_attributes PUBLIC "validator_min_max_attributes" "entities/validator_min_max_attributes.ent">
<!-- -->
<!ENTITY ui_component_attributes PUBLIC "ui_component_attributes" "entities/ui_component_attributes.ent">
<!-- -->
<!ENTITY ui_parameter_attributes PUBLIC "ui_parameter_attributes" "entities/ui_parameter_attributes.ent">
<!-- -->
<!ENTITY ui_for_attribute PUBLIC "ui_for_attribute" "entities/ui_for_attribute.ent">
<!-- -->
<!ENTITY ui_select_item_attributes PUBLIC "ui_select_item_attributes" "entities/ui_select_item_attributes.ent">
<!-- -->
<!ENTITY ui_select_items_attributes PUBLIC "ui_select_items_attributes" "entities/ui_select_items_attributes.ent">
<!-- -->
<!ENTITY html_anchor_attributes PUBLIC "html_anchor_attributes" "entities/html_anchor_attributes.ent">
<!-- -->
<!ENTITY html_button_attributes PUBLIC "html_button_attributes" "entities/html_button_attributes.ent">
<!-- -->
<!ENTITY html_event_handler_attributes PUBLIC "html_event_handler_attributes" "entities/html_events.ent">
<!-- -->
<!ENTITY html_form_attributes PUBLIC "html_form_attributes" "entities/html_form_attributes.ent">
<!-- -->
<!ENTITY spec_img_attributes PUBLIC "spec_img_attributes" "entities/spec_img_attributes.ent"> 
<!-- -->
<!ENTITY html_img_attributes PUBLIC "html_img_attributes" "entities/html_img_attributes.ent">
<!-- -->
<!ENTITY html_input_attributes PUBLIC "html_input_attributes" "entities/html_input_attributes.ent">
<!-- -->
<!ENTITY html_input_checkbox_attributes PUBLIC "html_input_checkbox_attributes" "entities/html_input_checkbox_attributes.ent">
<!-- -->
<!ENTITY html_input_radio_attributes PUBLIC "html_input_radio_attributes" "entities/html_input_radio_attributes.ent">
<!-- -->
<!ENTITY html_label_attributes PUBLIC "html_label_attributes" "entities/html_label_attributes.ent">
<!-- -->
<!ENTITY html_select_attributes PUBLIC "html_select_attributes" "entities/html_select_attributes.ent">
<!-- -->
<!ENTITY html_table_attributes PUBLIC "html_table_attributes" "entities/html_table_attributes.ent">
<!-- -->
<!ENTITY html_textarea_attributes PUBLIC "html_textarea_attributes" "entities/html_textarea_attributes.ent">
<!-- -->
<!ENTITY html_universal_attributes PUBLIC "html_universal_attributes" "entities/html_universal_attributes.ent">
<!-- -->
<!ENTITY html_style_attributes PUBLIC "html_style_attributes" "entities/html_style_attributes.ent">
<!-- -->
<!ENTITY html_control_attributes PUBLIC "html_control_attributes" "entities/html_control_attributes.ent">
<!-- -->
<!ENTITY html_control_events PUBLIC "html_control_events" "entities/html_control_events.ent">
<!-- -->
<!ENTITY html_events PUBLIC "html_events" "entities/html_events.ent">
<!-- -->
<!ENTITY html_input_events PUBLIC "html_input_events" "entities/html_input_events.ent">
<!-- -->
<!ENTITY ui_column_attributes PUBLIC "ui_column_attributes" "entities/ui_column_attributes.ent">
<!-- -->
<!ENTITY ui_command_attributes PUBLIC "ui_command_attributes" "entities/ui_command_attributes.ent">
<!-- -->
<!ENTITY ui_component_attributes PUBLIC "ui_component_attributes" "entities/ui_component_attributes.ent">
<!-- -->
<!ENTITY ui_data_attributes PUBLIC "ui_data_attributes" "entities/ui_data_attributes.ent">
<!-- -->
<!ENTITY ui_form_attributes PUBLIC "ui_form_attributes" "entities/ui_form_attributes.ent">
<!-- -->
<!ENTITY ui_graphic_attributes PUBLIC "ui_graphic_attributes" "entities/ui_graphic_attributes.ent">
<!-- -->
<!ENTITY ui_input_attributes PUBLIC "ui_input_attributes" "entities/ui_input_attributes.ent">
<!-- -->
<!ENTITY ui_message_attributes PUBLIC "ui_message_attributes" "entities/ui_message_attributes.ent">
<!-- -->
<!ENTITY ui_messages_attributes PUBLIC "ui_messages_attributes" "entities/ui_messages_attributes.ent">
<!-- -->
<!ENTITY ui_output_attributes PUBLIC "ui_output_attributes" "entities/ui_output_attributes.ent">
<!-- -->
<!ENTITY ui_panel_attributes PUBLIC "ui_panel_attributes" "entities/ui_panel_attributes.ent">
<!-- -->
<!ENTITY ui_parameter_attributes PUBLIC "ui_parameter_attributes" "entities/ui_parameter_attributes.ent">
<!-- -->
<!ENTITY ui_select_boolean_attributes PUBLIC "ui_select_boolean_attributes" "entities/ui_select_boolean_attributes.ent">
<!-- -->
<!ENTITY ui_select_many_attributes PUBLIC "ui_select_many_attributes" "entities/ui_select_many_attributes.ent">
<!-- -->
<!ENTITY ui_select_one_attributes PUBLIC "ui_select_one_attributes" "entities/ui_select_one_attributes.ent">
<!-- -->
<!ENTITY spec_img_attributes PUBLIC "spec_img_attributes" "entities/spec_img_attributes.ent">
<!-- -->
<!ENTITY spec_table_attributes PUBLIC "spec_table_attributes" "entities/spec_table_attributes.ent">
<!-- -->
<!ENTITY content_component_attributes PUBLIC "content_component_attributes" "entities/content_component_attributes.ent">
<!-- -->
<!ENTITY header_component_attributes PUBLIC "header_component_attributes" "entities/header_component_attributes.ent">
<!--
<!ENTITY standard_command_button_attributes PUBLIC "standard_command_button_attributes" "entities/standard_command_button_attributes.ent">
<!ENTITY standard_command_link_attributes PUBLIC "standard_command_link_attributes" "entities/standard_command_link_attributes.ent">
<!ENTITY standard_data_table_attributes PUBLIC "standard_data_table_attributes" "entities/standard_data_table_attributes.ent">
<!ENTITY standard_input_text_attributes PUBLIC "standard_input_text_attributes" "entities/standard_input_text_attributes.ent">
<!ENTITY standard_input_textarea_attributes PUBLIC "standard_input_textarea_attributes" "entities/standard_input_textarea_attributes.ent">
<!ENTITY standard_message_attributes PUBLIC "standard_message_attributes" "entities/standard_message_attributes.ent">
<!ENTITY standard_messages_attributes PUBLIC "standard_messages_attributes" "entities/standard_messages_attributes.ent">
<!ENTITY standard_output_label_attributes PUBLIC "standard_output_label_attributes" "entities/standard_output_label_attributes.ent">
<!ENTITY standard_output_text_attributes PUBLIC "standard_output_text_attributes" "entities/standard_output_text_attributes.ent">
<!ENTITY standard_panel_group_attributes PUBLIC "standard_panel_group_attributes" "entities/standard_panel_group_attributes.ent">
<!ENTITY standard_panel_grid_attributes PUBLIC "standard_panel_grid_attributes" "entities/standard_panel_grid_attributes.ent">
<!ENTITY standard_select_boolean_checkbox_attributes PUBLIC "standard_select_boolean_checkbox_attributes" "entities/standard_select_boolean_checkbox_attributes.ent">
<!ENTITY standard_select_many_checkbox_attributes PUBLIC "standard_select_many_checkbox_attributes" "entities/standard_select_many_checkbox_attributes.ent">
<!ENTITY standard_select_many_listbox_attributes PUBLIC "standard_select_many_listbox_attributes" "entities/standard_select_many_listbox_attributes.ent">
<!ENTITY standard_select_many_menu_attributes PUBLIC "standard_select_many_menu_attributes" "entities/standard_select_many_menu_attributes.ent">
<!ENTITY standard_select_one_listbox_attributes PUBLIC "standard_select_one_listbox_attributes" "entities/standard_select_one_listbox_attributes.ent">
<!ENTITY standard_select_one_menu_attributes PUBLIC "standard_select_one_menu_attributes" "entities/standard_select_one_menu_attributes.ent">
<!ENTITY standard_select_one_radio_attributes PUBLIC "standard_select_one_radio_attributes" "entities/standard_select_one_radio_attributes.ent">
-->

=== acdcjunior/richfaces-3.3.x/sandbox/ui/rex-resizable/src/main/config/component/resizable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE components PUBLIC "-//AJAX4JSF//CDK Generator config/EN"  "http://labs.jboss.com/jbossrichfaces/component-config.dtd" >
<components>
	<component>
		<name>org.richfaces.Resizable</name>
		<family>org.richfaces.Resizable</family>
		<classname>org.richfaces.component.html.HtmlResizable</classname>
		<superclass>org.richfaces.component.UIResizable</superclass>
		<description>
			<![CDATA[
			It presents the google map in JSF applications
            ]]>
		</description>
		<test />
		<renderer generate="true" override="true">
			<name>org.richfaces.ResizableRenderer</name>
			<template>resizable.jspx</template>
		</renderer>
		<tag>
			<name>resizable</name>
			<classname>org.richfaces.taglib.ResizableTag</classname>
			<superclass>
				org.ajax4jsf.webapp.taglib.HtmlComponentTagBase
			</superclass>
		</tag>

		&ui_component_attributes;
      	&html_events;
        &html_style_attributes;

		<property>
			<name>name</name>
			<classname>java.lang.String</classname>
			<description>
			    Name of the javascript variable that will be used to
			    access to the Ext.Resizable object. Might be otiopal if
			    the direct access is not required.
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>adjustments</name>
			<classname>java.lang.String</classname>
			<description>
			    String "auto" or an array [width, height]
			     with values to be added to the resize operation's new size
			     (defaults to [0,0])
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>animate</name>
			<classname>java.lang.String</classname>
			<description>
			    True to animate the resize
			    (not compatible with dynamic sizing, defaults to false)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>disableTrackOver</name>
			<classname>java.lang.String</classname>
			<description>
			    True to disable mouse tracking.
			    This is only applied at config time. (defaults to false)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>draggable</name>
			<classname>java.lang.String</classname>
			<description>
			    Convenience to initialize drag drop (defaults to false)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>duration</name>
			<classname>java.lang.String</classname>
			<description>
			    Animation duration if animate = true (defaults to .35)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>dynamic</name>
			<classname>java.lang.String</classname>
			<description>
			    True to resize the element while dragging instead of using a proxy (defaults to false)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>easing</name>
			<classname>java.lang.String</classname>
			<description>
			    Animation easing if animate = true (defaults to 'easingOutStrong')
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>enabled</name>
			<classname>java.lang.String</classname>
			<description>
			    False to disable resizing (defaults to true)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>handles</name>
			<classname>java.lang.String</classname>
			<description>
			    String consisting of the resize handles to display (defaults to undefined)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>height</name>
			<classname>java.lang.String</classname>
			<description>
			    The height of the element in pixels (defaults to 50)
			</description>
			<defaultvalue>"50"</defaultvalue>
		</property>
		<property>
			<name>heightIncrement</name>
			<classname>java.lang.String</classname>
			<description>
			    The increment to snap the height resize in pixels 
			    (dynamic must be true, defaults to 0)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>maxHeight</name>
			<classname>java.lang.String</classname>
			<description>
			    The maximum height for the element (defaults to 10000)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>maxWidth</name>
			<classname>java.lang.String</classname>
			<description>
			    The maximum width for the element (defaults to 10000)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>minHeight</name>
			<classname>java.lang.String</classname>
			<description>
			    The minimum height for the element (defaults to 5)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>minWidth</name>
			<classname>java.lang.String</classname>
			<description>
			    The minimum width for the element (defaults to 5)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>minX</name>
			<classname>java.lang.String</classname>
			<description>
			    The minimum allowed page X for the element
			    (only used for west resizing, defaults to 0)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>minY</name>
			<classname>java.lang.String</classname>
			<description>
			    The minimum allowed page Y for the element 
			    (only used for north resizing, defaults to 0)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>multiDirectional</name>
			<classname>java.lang.String</classname>
			<description>
			    Deprecated. The old style of adding multi-direction
			    resize handles, deprecated in favor of the handles
			    config option (defaults to false)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>pinned</name>
			<classname>java.lang.String</classname>
			<description>
			    True to ensure that the resize handles are always visible,
			    false to display them only when the user mouses over the
			    resizable borders. This is only applied at config time.
			    (defaults to false)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>preserveRatio</name>
			<classname>java.lang.String</classname>
			<description>
			    True to preserve the original ratio between height and width 
			    during resize (defaults to false)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>resizeChild</name>
			<classname>java.lang.String</classname>
			<description>
			    True to resize the first child, or id/element to resize
			    (defaults to false)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>transparent</name>
			<classname>java.lang.String</classname>
			<description>
			    True for transparent handles. This is only applied at
			    config time. (defaults to false)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>width</name>
			<classname>java.lang.String</classname>
			<description>
			    The width of the element in pixels (defaults to 100)
			</description>
			<defaultvalue>"100"</defaultvalue>
		</property>
		<property>
			<name>widthIncrement</name>
			<classname>java.lang.String</classname>
			<description>
			    The increment to snap the width resize in pixels
			    (dynamic must be true, defaults to 0)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>wrap</name>
			<classname>java.lang.String</classname>
			<description>
			    Apply to the child element directly. Important for some element, such
			    as image of textarea
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
	</component>
</components>

=== acdcjunior/richfaces-3.3.x/branches/community/3.3.X/ui/core/src/main/config/component/repeat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE components 
        PUBLIC "-//AJAX4JSF//CDK Generator config/EN"
        "http://labs.jboss.com/jbossrichfaces/component-config.dtd"
[
	<!ENTITY universal_html_attributes   SYSTEM "html_universal_attributes.xml">	
]>

<components>
     	<component>
		<name>org.ajax4jsf.Repeat</name>
		<family>javax.faces.Data</family>
		<classname>org.ajax4jsf.component.html.HtmlAjaxRepeat</classname>
		<superclass>org.ajax4jsf.component.UIRepeat</superclass>
		<test />
		<description>
			<![CDATA[
    ]]>
		</description>
		<displayname>Ajax-enabled repeater</displayname>
		<icon>icon</icon>
		<renderer generate="false" override="false">
			<name>org.ajax4jsf.components.RepeatRenderer</name>
			<classname>
				org.ajax4jsf.renderkit.html.RepeatRenderer
			</classname>
			<!-- 
				<superclass>javax.faces.renderer.Renderer</superclass>
			-->
			<description></description>
			<displayname>
				renderer for Ajax-enabled repeater
			</displayname>
			<icon>icon</icon>
		</renderer>
		<tag>
			<name>repeat</name>
			<classname>org.ajax4jsf.taglib.html.jsp.AjaxRepeat</classname>
			<superclass>
				org.ajax4jsf.webapp.taglib.UIComponentTagBase
			</superclass>
			<test />
			<displayname>Ajax-enabled repeater</displayname>
			<icon>icon</icon>
		</tag>
		&ui_data_attributes;
		&ui_component_attributes;
		<property>
			<name>componentState</name>
			<classname>org.ajax4jsf.model.DataComponentState</classname>
			<description>It defines EL-binding  for a component state for saving or redefinition.</description>
		</property>		
		<property el="false">
			<name>stateVar</name>
			<classname>java.lang.String</classname>
			<description>The attribute  provides access to a component state on the client side.</description>
		</property>		
		<property>
			<name>value</name>
			<classname>java.lang.Object</classname>
			<description>The current value for this component.</description>
		</property>
		<property>
			<name>ajaxKeys</name>
			<classname>java.util.Set</classname>
			<description>This attribute defines row keys that are updated after an AJAX request.</description>
		</property>
		<property el="false">
			<name>rowKeyVar</name>
			<classname>java.lang.String</classname>
			<description>The attribute  provides access to a row key in a Request scope.</description>
		</property>
		<property hidden="true">
			<name>rowKey</name>
			<classname>java.lang.Object</classname>
			<description>RowKey is a representation of an identifier for a specific data row.</description>
		</property>
     		<property>
     			<name>rowKeyConverter</name>
     			<classname>javax.faces.convert.Converter</classname>
     			<description>Converter for a row key object</description>
     		</property>	

	</component>     
</components>

=== acdcjunior/richfaces-3.3.x/branches/community/3.3.X/ui/hotKey/src/main/config/component/hotKey.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE components PUBLIC "-//AJAX4JSF//CDK Generator config/EN"  "http://labs.jboss.com/jbossrichfaces/component-config.dtd">

<components>
	<component>
		<name>org.richfaces.HotKey</name>
		<family>org.richfaces.HotKey</family>
		<classname>org.richfaces.component.html.HtmlHotKey</classname>
		<superclass>org.richfaces.component.UIHotKey</superclass>
		
		<test />
		
		<description>
			The &lt;rich:hotKey&gt; component allows to register hot keys for the page or particular elements and to define client side processing functions for these keys.
		</description>
		<renderer generate="true" override="true">
			<name>org.richfaces.HotKeyRenderer</name>
			<template>org/richfaces/htmlHotKey.jspx</template>
		</renderer>
		<tag>
			<name>hotKey</name>
			<classname>org.richfaces.taglib.HotKeyTag</classname>
			<superclass>
				org.ajax4jsf.webapp.taglib.HtmlComponentTagBase
			</superclass>
			<test />
		</tag>
		<!--
		<taghandler>
			<classname>org.ajax4jsf.tag.TestHandler</classname>
		</taghandler>
		-->
		&ui_component_attributes;
		<property>
			<name>key</name>
			<classname>java.lang.String</classname>
			<description>
				Defines the hotkey itself
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>timing</name>
			<classname>java.lang.String</classname>
			<description>
				Defines the time when the hotkey is registered. Possible values are &quot;immediate&quot; (by default), &quot;onload&quot;, and &quot;onregistercall&quot;.
				Default value is &quot;immediate&quot;
			</description>
			<defaultvalue>"immediate"</defaultvalue>
		</property>
		<property>
			<name>selector</name>
			<classname>java.lang.String</classname>
			<description>
				Defines a selector for query
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>type</name>
			<classname>java.lang.String</classname>
			<description>
				Defines the type of a keyboard event (onkeyup, onkeypress, etc.)
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>disableInInput</name>
			<classname>java.lang.Boolean</classname>
			<description>
				Disables the hotkeys activated on input elements when the value of this attribute is &quot;true&quot;.
			</description>
		</property>
		<property>
			<name>checkParent</name>
			<classname>java.lang.Boolean</classname>
			<description>
				Defines the hotkey handling of events generated by child components nested into the parent component to which the &lt;rich:hotKey&gt; is attached.
			</description>
		</property>
		<property>
			<name>handler</name>
			<classname>java.lang.String</classname>
			<description>
				Defines the JavaScript function name which is called on hotkey activation
			</description>
			<defaultvalue>""</defaultvalue>
		</property>
		<property>
			<name>disableInInputTypes</name>
			<classname>java.lang.String</classname>
			<description>Defines the types of the inputs not to be influenced with hotKey component. Possible values: buttons, texts and all (default). By default it is empty and this means ALL the types.</description>
		</property>
	</component>
</components>

=== acdcjunior/richfaces-3.3.x/branches/community/3.3.X/sandbox/ui/panel2/src/main/config/component/panel2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE components PUBLIC "-//AJAX4JSF//CDK Generator config/EN"  "http://labs.jboss.com/jbossrichfaces/component-config.dtd" >
<components>
	<component>
		<name>org.richfaces.panel2</name>
		<family>org.richfaces.panel2</family>
		<classname>org.richfaces.component.html.HtmlPanel2</classname>
		<superclass>org.richfaces.component.UIPanel2</superclass>
		<test>
			<classname>org.richfaces.component.html.HtmlPanel2ComponentTest</classname>
			<superclassname>org.ajax4jsf.tests.AbstractAjax4JsfTestCase</superclassname>
		</test>
		<description>
			<![CDATA[A skinnable panel that is rendered as a bordered rectangle. The header is 
    added using a facet with the attribute, name="header".
   			 ]]>
		</description>
		<renderer generate="true" override="true">
			<name>org.richfaces.Panel2Renderer</name>
			<template>panel2.jspx</template>
		</renderer>
		<tag>
			<name>panel2</name>
			<classname>org.richfaces.taglib.Panel2Tag</classname>
			<superclass>
				org.ajax4jsf.webapp.taglib.HtmlComponentTagBase
			</superclass>
			<test>
				<classname>org.richfaces.taglib.HtmlPanel2TagTest</classname>
				<superclassname>org.ajax4jsf.tests.AbstractJspTestCase</superclassname>
			</test>
			
		</tag>
		&ui_component_attributes;
      	&html_events;
        &html_style_attributes;
		<property>
			<name>headerClass</name>
			<classname>java.lang.String</classname>
			<description>
				A class that defines a style for a panel header
			</description>
		</property>
		<property>
			<name>bodyClass</name>
			<classname>java.lang.String</classname>
			<description>
				A class that defines a style for a panel content
			</description>
		</property>
	</component>
</components>
