=== acdcjunior/richfaces-3.3.x/branches/community/3.3.X/cdk/generator/src/main/resources/META-INF/schema/component-config.dtd
<!-- Defenition of component configuration for generator 
	PUBLIC-ID "-//AJAX4JSF//CDK Generator config/EN"
	SYSTEM-ID http://labs.jboss.com/jbossrichfaces/component-config.dtd -->
<!-- Root element for components and renderers  -->	
<!ELEMENT components (component*,renderer*,listener*,validator*,converter*,function*) >
<!-- Component description with common properties, tags and renderers descriptions  -->	
<!ELEMENT component (name,family?,classname?,superclass?,test*,description?,displayname?,icon?,facet*,renderer*,tag?,taghandler?,(include|properties|property)*)>
<!-- Validator description with properties and tags -->
<!ELEMENT validator (id,classname?,superclass?,test*,description?,displayname?,icon?,tag?,taghandler?,(include|properties|property)*)>
<!-- Validator description with properties and tags -->
<!ELEMENT converter (id,classname?,superclass?,test*,description?,displayname?,icon?,tag?,taghandler?,(include|properties|property)*)>

<!ELEMENT function (name,description?,method)>

<!-- components with generate=false not produce component class, 
     use for describe superclasses for other components -->
<!ATTLIST component
	generate (true|false) "true" 
	>
	
<!-- validators with generate=false do not generate a class -->
<!ATTLIST validator
	generate (true|false) "true" 
	>
	
<!-- converters with generate=false do not generate a class -->
<!ATTLIST converter
	generate (true|false) "true" 
	>

<!-- Common component parameters -->
<!-- Name of component/renderer/property -->
<!ELEMENT name (#PCDATA)>
<!-- Id of the validator/converter -->
<!ELEMENT id (#PCDATA)>
<!-- Component family -->
<!ELEMENT family (#PCDATA)>
<!-- Element Description for config files -->
<!ELEMENT description ANY>
<!-- Element Dispaly name , for config files -->
<!ELEMENT displayname ANY>
<!-- Element icon image , for config files -->
<!ELEMENT icon (#PCDATA)>
<!-- component allowed facet  name , for config files -->
<!ELEMENT facet (name,displayname?,description?)>
<!-- Full name of Java class -->
<!ELEMENT classname (#PCDATA)>
<!-- Full name of Java super class -->
<!ELEMENT superclass (#PCDATA)>
<!-- Define renderer for this component -->
<!ELEMENT renderer (name,family?,(classname|template),superclass?,description?,displayname?,icon?,facet?,renderkit?)>
<!-- Define render kit Id for renderer -->
<!ELEMENT renderkit (#PCDATA)>
<!-- Template file name -->
<!ELEMENT template (#PCDATA)>
<!-- Fully-qualified method name and signature -->
<!ELEMENT method (#PCDATA)>

<!ATTLIST renderer
	generate (true|false) "false" 
	override (true|false) "false" 
	>

<!-- Define JSP tag for this component -->
<!ELEMENT tag (name,classname,superclass?,test*,taglib?,description?,displayname?,icon?)>
<!ATTLIST tag
	generate (true|false) "true" 
	bodyContent (JSP|empty) "JSP" 
	>

<!ELEMENT test (classname?,superclassname?)>
<!--!ELEMENT classname (#PCDATA)-->
<!ELEMENT superclassname (#PCDATA)>

<!-- Define JSP tag for this component -->
<!ELEMENT taghandler (name?,classname,superclass?,description?,displayname?,icon?)>
<!ATTLIST taghandler
	generate (true|false) "false" 
	>

<!ELEMENT listener (name,listenerclass,componentclass,eventclass,methodname?,tag?,taghandler?,property*)>

<!ELEMENT listenerclass (#PCDATA)>
<!ELEMENT eventclass (#PCDATA)>
<!ELEMENT componentclass (#PCDATA)>
<!ELEMENT methodname (#PCDATA)>

<!-- Short name of taglib for this tag - for generate set of taglibs in single task -->
<!ELEMENT taglib (#PCDATA)>

<!-- proprties group for included entity -->
<!ELEMENT properties ((include|properties|property)*)>

<!-- Define single property for this component -->
<!ELEMENT property (name,classname?,description?,defaultvalue?,methodargs?,returntype?,alias*)>

<!-- default value for property -->
<!ELEMENT defaultvalue (#PCDATA)>

<!-- comma-separated list of method call parameters classes for Method-binded property -->
<!ELEMENT methodargs (#PCDATA)>

<!-- return type for method call parameters classes for Method-binded property -->
<!ELEMENT returntype (#PCDATA)>

<!-- alias for property in JSP tag -->
<!ELEMENT alias (#PCDATA)>

<!ATTLIST property 
	el (true|false) "true"
	elonly (true|false) "false"
	hidden (true|false) "false"
	exist (true|false) "false"
	raw (true|false) "false"
	existintag (true|false) "false"
	attachedstate (true|false) "false"
	transient (true|false) "false"
	required (true|false) "false"
	disabled (true|false) "false"	
	>
<!-- include pre-defined properties set -->
<!ELEMENT include EMPTY >
<!ATTLIST include 
      href CDATA #REQUIRED
>

<!-- pre-defined entities for common components properties -->
<!ENTITY html_attributes   PUBLIC "html_universal_attributes" "entities/html_universal_attributes.ent">	
<!-- pre-defined entities for common component events -->
<!ENTITY html_events   PUBLIC "html_events" "entities/html_events.ent">	
<!-- pre-defined entities for common controls' events -->
<!ENTITY html_control_events   PUBLIC "html_control_events" "entities/html_control_events.ent">	
<!-- -->
<!ENTITY ajax_region_attributes PUBLIC "ajax_region_attributes" "entities/ajax_region_attributes.ent">
<!-- -->
<!ENTITY ajax_component_attributes PUBLIC "ajax_component_attributes" "entities/ajax_component_attributes.ent">
<!-- -->
<!ENTITY ajax_output_attributes PUBLIC "ajax_output_attributes" "entities/ajax_output_attributes.ent">
<!-- -->
<!ENTITY ajax_dnd_attributes PUBLIC "ajax_dnd_attributes" "entities/ajax_dnd_attributes.ent">
<!-- -->
<!ENTITY dropzone_attributes PUBLIC "dropzone_attributes" "entities/dropzone_attributes.ent">
<!-- -->
<!ENTITY draggable_attributes PUBLIC "draggable_attributes" "entities/draggable_attributes.ent">

<!-- imported from myfaces -->

<!-- -->
<!ENTITY validator_min_max_attributes PUBLIC "validator_min_max_attributes" "entities/validator_min_max_attributes.ent">
<!-- -->
<!ENTITY ui_component_attributes PUBLIC "ui_component_attributes" "entities/ui_component_attributes.ent">
<!-- -->
<!ENTITY ui_parameter_attributes PUBLIC "ui_parameter_attributes" "entities/ui_parameter_attributes.ent">
<!-- -->
<!ENTITY ui_for_attribute PUBLIC "ui_for_attribute" "entities/ui_for_attribute.ent">
<!-- -->
<!ENTITY ui_select_item_attributes PUBLIC "ui_select_item_attributes" "entities/ui_select_item_attributes.ent">
<!-- -->
<!ENTITY ui_select_items_attributes PUBLIC "ui_select_items_attributes" "entities/ui_select_items_attributes.ent">
<!-- -->
<!ENTITY html_anchor_attributes PUBLIC "html_anchor_attributes" "entities/html_anchor_attributes.ent">
<!-- -->
<!ENTITY html_button_attributes PUBLIC "html_button_attributes" "entities/html_button_attributes.ent">
<!-- -->
<!ENTITY html_event_handler_attributes PUBLIC "html_event_handler_attributes" "entities/html_events.ent">
<!-- -->
<!ENTITY html_form_attributes PUBLIC "html_form_attributes" "entities/html_form_attributes.ent">
<!-- -->
<!ENTITY spec_img_attributes PUBLIC "spec_img_attributes" "entities/spec_img_attributes.ent"> 
<!-- -->
<!ENTITY html_img_attributes PUBLIC "html_img_attributes" "entities/html_img_attributes.ent">
<!-- -->
<!ENTITY html_input_attributes PUBLIC "html_input_attributes" "entities/html_input_attributes.ent">
<!-- -->
<!ENTITY html_input_checkbox_attributes PUBLIC "html_input_checkbox_attributes" "entities/html_input_checkbox_attributes.ent">
<!-- -->
<!ENTITY html_input_radio_attributes PUBLIC "html_input_radio_attributes" "entities/html_input_radio_attributes.ent">
<!-- -->
<!ENTITY html_label_attributes PUBLIC "html_label_attributes" "entities/html_label_attributes.ent">
<!-- -->
<!ENTITY html_select_attributes PUBLIC "html_select_attributes" "entities/html_select_attributes.ent">
<!-- -->
<!ENTITY html_table_attributes PUBLIC "html_table_attributes" "entities/html_table_attributes.ent">
<!-- -->
<!ENTITY html_textarea_attributes PUBLIC "html_textarea_attributes" "entities/html_textarea_attributes.ent">
<!-- -->
<!ENTITY html_universal_attributes PUBLIC "html_universal_attributes" "entities/html_universal_attributes.ent">
<!-- -->
<!ENTITY html_style_attributes PUBLIC "html_style_attributes" "entities/html_style_attributes.ent">
<!-- -->
<!ENTITY html_control_attributes PUBLIC "html_control_attributes" "entities/html_control_attributes.ent">
<!-- -->
<!ENTITY html_control_events PUBLIC "html_control_events" "entities/html_control_events.ent">
<!-- -->
<!ENTITY html_events PUBLIC "html_events" "entities/html_events.ent">
<!-- -->
<!ENTITY html_input_events PUBLIC "html_input_events" "entities/html_input_events.ent">
<!-- -->
<!ENTITY ui_column_attributes PUBLIC "ui_column_attributes" "entities/ui_column_attributes.ent">
<!-- -->
<!ENTITY ui_command_attributes PUBLIC "ui_command_attributes" "entities/ui_command_attributes.ent">
<!-- -->
<!ENTITY ui_component_attributes PUBLIC "ui_component_attributes" "entities/ui_component_attributes.ent">
<!-- -->
<!ENTITY ui_data_attributes PUBLIC "ui_data_attributes" "entities/ui_data_attributes.ent">
<!-- -->
<!ENTITY ui_form_attributes PUBLIC "ui_form_attributes" "entities/ui_form_attributes.ent">
<!-- -->
<!ENTITY ui_graphic_attributes PUBLIC "ui_graphic_attributes" "entities/ui_graphic_attributes.ent">
<!-- -->
<!ENTITY ui_input_attributes PUBLIC "ui_input_attributes" "entities/ui_input_attributes.ent">
<!-- -->
<!ENTITY ui_message_attributes PUBLIC "ui_message_attributes" "entities/ui_message_attributes.ent">
<!-- -->
<!ENTITY ui_messages_attributes PUBLIC "ui_messages_attributes" "entities/ui_messages_attributes.ent">
<!-- -->
<!ENTITY ui_output_attributes PUBLIC "ui_output_attributes" "entities/ui_output_attributes.ent">
<!-- -->
<!ENTITY ui_panel_attributes PUBLIC "ui_panel_attributes" "entities/ui_panel_attributes.ent">
<!-- -->
<!ENTITY ui_parameter_attributes PUBLIC "ui_parameter_attributes" "entities/ui_parameter_attributes.ent">
<!-- -->
<!ENTITY ui_select_boolean_attributes PUBLIC "ui_select_boolean_attributes" "entities/ui_select_boolean_attributes.ent">
<!-- -->
<!ENTITY ui_select_many_attributes PUBLIC "ui_select_many_attributes" "entities/ui_select_many_attributes.ent">
<!-- -->
<!ENTITY ui_select_one_attributes PUBLIC "ui_select_one_attributes" "entities/ui_select_one_attributes.ent">
<!-- -->
<!ENTITY spec_img_attributes PUBLIC "spec_img_attributes" "entities/spec_img_attributes.ent">
<!-- -->
<!ENTITY spec_table_attributes PUBLIC "spec_table_attributes" "entities/spec_table_attributes.ent">
<!-- -->
<!ENTITY content_component_attributes PUBLIC "content_component_attributes" "entities/content_component_attributes.ent">
<!-- -->
<!ENTITY header_component_attributes PUBLIC "header_component_attributes" "entities/header_component_attributes.ent">
<!--
<!ENTITY standard_command_button_attributes PUBLIC "standard_command_button_attributes" "entities/standard_command_button_attributes.ent">
<!ENTITY standard_command_link_attributes PUBLIC "standard_command_link_attributes" "entities/standard_command_link_attributes.ent">
<!ENTITY standard_data_table_attributes PUBLIC "standard_data_table_attributes" "entities/standard_data_table_attributes.ent">
<!ENTITY standard_input_text_attributes PUBLIC "standard_input_text_attributes" "entities/standard_input_text_attributes.ent">
<!ENTITY standard_input_textarea_attributes PUBLIC "standard_input_textarea_attributes" "entities/standard_input_textarea_attributes.ent">
<!ENTITY standard_message_attributes PUBLIC "standard_message_attributes" "entities/standard_message_attributes.ent">
<!ENTITY standard_messages_attributes PUBLIC "standard_messages_attributes" "entities/standard_messages_attributes.ent">
<!ENTITY standard_output_label_attributes PUBLIC "standard_output_label_attributes" "entities/standard_output_label_attributes.ent">
<!ENTITY standard_output_text_attributes PUBLIC "standard_output_text_attributes" "entities/standard_output_text_attributes.ent">
<!ENTITY standard_panel_group_attributes PUBLIC "standard_panel_group_attributes" "entities/standard_panel_group_attributes.ent">
<!ENTITY standard_panel_grid_attributes PUBLIC "standard_panel_grid_attributes" "entities/standard_panel_grid_attributes.ent">
<!ENTITY standard_select_boolean_checkbox_attributes PUBLIC "standard_select_boolean_checkbox_attributes" "entities/standard_select_boolean_checkbox_attributes.ent">
<!ENTITY standard_select_many_checkbox_attributes PUBLIC "standard_select_many_checkbox_attributes" "entities/standard_select_many_checkbox_attributes.ent">
<!ENTITY standard_select_many_listbox_attributes PUBLIC "standard_select_many_listbox_attributes" "entities/standard_select_many_listbox_attributes.ent">
<!ENTITY standard_select_many_menu_attributes PUBLIC "standard_select_many_menu_attributes" "entities/standard_select_many_menu_attributes.ent">
<!ENTITY standard_select_one_listbox_attributes PUBLIC "standard_select_one_listbox_attributes" "entities/standard_select_one_listbox_attributes.ent">
<!ENTITY standard_select_one_menu_attributes PUBLIC "standard_select_one_menu_attributes" "entities/standard_select_one_menu_attributes.ent">
<!ENTITY standard_select_one_radio_attributes PUBLIC "standard_select_one_radio_attributes" "entities/standard_select_one_radio_attributes.ent">
-->

=== acdcjunior/richfaces-3.3.x/ui/core/src/main/config/component/region.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE components 
        PUBLIC "-//AJAX4JSF//CDK Generator config/EN"
        "http://labs.jboss.com/jbossrichfaces/component-config.dtd"
[
	<!ENTITY universal_html_attributes   SYSTEM "html_universal_attributes.xml">	
]>

<components>
     	<component>
		<name>org.ajax4jsf.AjaxRegion</name>
		<family>org.ajax4jsf.AjaxRegion</family>
		<classname>org.ajax4jsf.component.html.HtmlAjaxRegion</classname>
		<superclass>org.ajax4jsf.component.UIAjaxRegion</superclass>
		<test />
		<description>
			<![CDATA[Root view for ajax areas on the page. It must either be a 
			nested tag inside the <body> tag inside of the 
			<html> tag or, if selfRendered="true", it can be 
			in any part of the page. Decode: Obtain the Map from the
			"requestParameterMap" property of the ExternalContext. If
			the value in Map for the "AJAXREQUEST" is not null, and equals
			to value of the "clientId" property of the component, set
			ajaxRequest property to true, create AjaxEvent around the
			component, and pass it to the queueEvent() method of the
			component, which must be an instance of AjaxContainer
			Rendering : On standart JSF request, insert &lt;script&gt;
			element with link to Ajax client-side javaScript at start
			tag position. If performed Ajax request, invoke listeners
			and render only affected to request components. List of
			clientId of rendered components set as special response
			headers and hidden &lt;span&gt; html element. With
			'selfRendered' attribute set as "true", render affected
			components at Invoke Application phase - produce
			&lt;html&gt;&lt;body&gt; elements, render affected
			components and set responseComplete at FacesContext. In this
			case, JSP page not rendered. Since, Jstl or other JSP tags
			must not be used inside &lt;a4jx:region&gt; with immediate
			flag.]]>
		</description>
		<displayname>Ajax Region</displayname>
		<icon>icon</icon>
		<renderer generate="false" override="false">
			<name>org.ajax4jsf.components.AjaxRegionRenderer</name>
			<classname>
				org.ajax4jsf.renderkit.html.AjaxRegionRenderer
			</classname>
			<!-- 
				<superclass>javax.faces.renderer.Renderer</superclass>
			-->
			<description>test renderer description</description>
			<displayname>renderer for Ajax Region</displayname>
			<icon>icon</icon>
		</renderer>
		<tag>
			<name>region</name>
			<classname>org.ajax4jsf.taglib.html.jsp.AjaxRegion</classname>
			<superclass>
				org.ajax4jsf.webapp.taglib.HtmlComponentTagBase
			</superclass>
			<test />
			<description>
				<![CDATA[This tag defines a part of the JSF Tree that is to be decoded on the
    server side during AJAX request processing]]>
			</description>
			<displayname>Ajax Region</displayname>
			<icon>icon</icon>
		</tag>
		&ui_component_attributes;
		&ajax_region_attributes;
		<property>
			<name>renderRegionOnly</name>
			<classname>boolean</classname>
			<description>
				Flag to disable rendering in AJAX responses content
				outside of active region. If this attribute set to
				"true" , no one of the components outside of region will
				be included to AJAX response. If set to "false", search
				for components to include in response will be performed
				on all tree. Default value is  &quot;false&quot;.
			</description>
			<defaultvalue>false</defaultvalue>
		</property>
	</component>
     
</components>

=== acdcjunior/richfaces-3.3.x/branches/community/3.3.X/ui/editor/src/main/config/component/editor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE components PUBLIC "-//AJAX4JSF//CDK Generator config/EN"  "http://labs.jboss.com/jbossrichfaces/component-config.dtd" >
<components>
	<component>
		<name>org.richfaces.Editor</name>
		<family>org.richfaces.Editor</family>
		<classname>org.richfaces.component.html.HtmlEditor</classname>
		<superclass>org.richfaces.component.UIEditor</superclass>
		<test>
			<classname>org.richfaces.component.html.HtmlEditorComponentTest</classname>
			<superclassname>org.ajax4jsf.tests.AbstractAjax4JsfTestCase</superclassname>
		</test>
		<description>			
		</description>
		<renderer generate="true" override="true">
			<name>org.richfaces.EditorRenderer</name>
			<template>editor.jspx</template>
		</renderer>
		<tag>
			<name>editor</name>
			<classname>org.richfaces.taglib.EditorTag</classname>
			<superclass>
				org.ajax4jsf.webapp.taglib.HtmlComponentTagBase
			</superclass>
			<test>
			</test>	
		</tag>
		&ui_component_attributes;
		&ui_input_attributes;
		&ui_output_attributes;
		<property>
	    	<name>style</name>
	    	<classname>java.lang.String</classname>
	    	<description>CSS style(s) is/are to be applied when this component is rendered</description>
	    	<defaultvalue><![CDATA[""]]></defaultvalue>
		</property>
		<property>
	    	<name>styleClass</name>
	    	<classname>java.lang.String</classname>
	     	<description>Corresponds to the HTML class attribute</description>
	    	<defaultvalue><![CDATA[""]]></defaultvalue>
		</property>
		<property hidden="true">
			<name>type</name>
			<classname>java.lang.String</classname>
			<description>
				Sets editor type. Default value is &quot;TinyMCE&quot;
			</description>
			<defaultvalue>"TinyMCE"</defaultvalue>
		</property>
		<property>
			<name>width</name>
			<classname>java.lang.Integer</classname>
			<description>
				Attribute defines width of component.
			</description>
		</property>
		<property>
			<name>height</name>
			<classname>java.lang.Integer</classname>
			<description>
				Attribute defines height of component.
			</description>
		</property>
		<property>
			<name>theme</name>
			<classname>java.lang.String</classname>
			<description>
				Attribute defines Editor theme
			</description>
		</property>
		<property>
			<name>useSeamText</name>
			<classname>boolean</classname>
			<description>
				Attribute defines if model value should be converted to Seam Text. Default value is &quot;false&quot;
			</description>
			<defaultvalue>false</defaultvalue>
		</property>
		
		<property>
			<name>plugins</name>
			<classname>java.lang.String</classname>
			<description>
				Attribute defines Editor plugins
			</description>
		</property>
		<property>
			<name>readonly</name>
			<classname>boolean</classname>
			<description>
				Attribute defines Editor is readonly
			</description>
		</property>
		<property>
			<name>language</name>
			<classname>java.lang.String</classname>
			<description>
				Attribute defines Editor language
			</description>
		</property>
		<property>
			<name>autoResize</name>
			<classname>boolean</classname>
			<description>
				Attribute enables to get the Editor area to resize to the boundaries of the contents.
			</description>
		</property>
		<property>
			<name>tabindex</name>
			<classname>java.lang.String</classname>
			<description>
				In visual mode the attribute works the same way as "tab_focus" TinyMCE&apos;s property the attribute enables 
				you to specify an element ID to focus, when the TAB  key  is pressed .
				You can also use the special ":prev" and ":next"  values that will then place the focus on 
				an input element placed before/after the TinyMCE instance in the DOM. 
				While in "source" mode the attribute works like standard HTML tabindex attribute.
			</description>
		</property>
		<property>
			<name>oninit</name>
			<classname>java.lang.String</classname>
			<description>
				HTML: script expression; initialization of the editor's instances are finished
			</description>
		</property>
		<property>
			<name>onchange</name>
			<classname>java.lang.String</classname>
			<description>
				HTML: script expression; content is modified by TinyMCE.
			</description>
		</property>
		<property>
			<name>onsave</name>
			<classname>java.lang.String</classname>
			<description>
				HTML: script expression; the contents is extracted/saved.
			</description>
		</property>
		<property>
			<name>onsetup</name>
			<classname>java.lang.String</classname>
			<description>
				HTML: script expression; to add events to editor instances before they get rendered. 
			</description>
		</property>
		<property>
			<name>configuration</name>
			<classname>java.lang.String</classname>
			<description>
				Attribute defines configuration properties file name
			</description>
		</property>
		<property>
			<name>customPlugins</name>
			<classname>java.lang.String</classname>
			<description>
				Attribute defines property file name witch contains descriptors of custom plugins
			</description>
		</property>
		<property hidden="true">
			<name>localValueSet</name>
			<classname>boolean</classname>
			<description>localValueSet</description>
		</property>
		<property hidden="true">
			<name>valid</name>
			<classname>boolean</classname>
			<description>valid</description>
		</property>
		<property>
			<name>skin</name>
			<classname>java.lang.String</classname>
			<description>
				Attribute defines Editor skin
			</description>
		</property>
		<property>
			<name>viewMode</name>
			<classname>java.lang.String</classname>
			<description>
				Attribute defines if tinyMCE WYSIWYG should be disabled. Default value is &quot;visual&quot;
			</description>
			<defaultvalue>"visual"</defaultvalue>
		</property>
		<property>
			<name>dialogType</name>
			<classname>java.lang.String</classname>
			<description>
				Attribute defines how dialogs/popups should be opened. Default value is &quot;modal&quot;
			</description>
			<defaultvalue>"modal"</defaultvalue>
		</property>
		<property>
			<name>label</name>
			<classname>java.lang.String</classname>
			<description>A localized user presentable name for this component.</description>
		</property>
	</component>
</components>

=== acdcjunior/richfaces-3.3.x/branches/community/3.3.X/ui/core/src/main/config/component/form.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE components 
        PUBLIC "-//AJAX4JSF//CDK Generator config/EN"
        "http://labs.jboss.com/jbossrichfaces/component-config.dtd"
[
	<!ENTITY universal_html_attributes   SYSTEM "html_universal_attributes.xml">	
]>

<components>
     	<component generate="true">
		<name>org.ajax4jsf.Form</name>
		<family>javax.faces.Form</family>
		<classname>org.ajax4jsf.component.html.AjaxForm</classname>
		<superclass>org.ajax4jsf.component.UIAjaxForm</superclass>
		<test />
		<description>
			<![CDATA[
		Ajax-related version of html form. Main difference with original component - all hidden fields,
		necessary to command links alwais rendered, not depended of rendering links on initial page.
		]]>
		</description>
		<renderer>
			<name>org.ajax4jsf.FormRenderer</name>
			<classname>
				org.ajax4jsf.renderkit.html.AjaxFormRenderer
			</classname>
		</renderer>
		<tag>
			<name>form</name>
			<classname>org.ajax4jsf.taglib.html.jsp.FormTag</classname>
			<superclass>
				org.ajax4jsf.webapp.taglib.UIComponentTagBase
			</superclass>
			<test />
			<displayname>Ajax-related version of html form</displayname>
			<icon>icon</icon>
		<test />
		</tag>
		<taghandler>
			<classname>org.ajax4jsf.webapp.taglib.AjaxComponentHandler</classname>
		</taghandler>
		&ui_component_attributes;
		&html_form_attributes;
		&ajax_component_attributes;
		&html_style_attributes;
		<property>
			<name>ajaxSubmit</name>
			<classname>boolean</classname>
			<description>If &quot;true&quot;, it becomes possible to set AJAX submission way for any components inside	.</description>
		</property>
		<property>
			<name>ignoreDupResponses</name>
			<classname>boolean</classname>
			<description>
Attribute allows to ignore an Ajax Response produced by a request if the newest 'similar' request is
in a queue already. ignoreDupResponses="true" does not cancel the request while it is processed on the server,
but just allows to avoid unnecessary updates on the client side if the response isn't actual now			
			</description>
		</property>
		<property>
			<name>timeout</name>
			<classname>int</classname>
			<description>Timeout ( in ms ) for request.</description>
		</property>
		<property>
			<name>prependId</name>
			<classname>boolean</classname>
			<description>The flag indicating whether or not this form should prepend its id to its descendent id during the clientId generation process. If this flag is not set, the default value is &quot;true&quot;.</description>
		</property>		
		<property disabled="true">
			<name>submitted</name>
		</property>
	</component>
	<component generate="false">
		<name>javax.faces.HtmlCommandLink</name>
		<family>javax.faces.Command</family>
		<classname>
			javax.faces.component.html.HtmlCommandLink
		</classname>
		<superclass>
			javax.faces.component.html.HtmlCommandLink
		</superclass>
		<description>
			<![CDATA[
		Ajax-related version of html commandLink. Single difference with original component - all hidden fields,
		necessary to command links alwais rendered, not depended of rendering links on initial page.
		]]>
		</description>
		<renderer>
			<name>org.ajax4jsf.HtmlCommandLinkRenderer</name>
			<classname>
				org.ajax4jsf.renderkit.html.HtmlCommandLinkRenderer
			</classname>
		</renderer>
		<tag>
			<name>htmlCommandLink</name>
			<classname>
				org.ajax4jsf.taglib.html.jsp.HtmlCommandLinkTag
			</classname>
			<superclass>
				org.ajax4jsf.webapp.taglib.UIComponentTagBase
			</superclass>
			<displayname>
				Ajax-related version of html command link
			</displayname>
			<icon>icon</icon>
			<test/>
		</tag>
		
		&html_universal_attributes;
		&ui_command_attributes;
		&html_anchor_attributes;
		&html_events;
		<property>
        <name>disabled</name>
        <classname>boolean</classname>
        <description>When set for a form control, this boolean attribute disables the control for your input.</description>
    </property> 
	</component>     
</components>
